### ISSUE TITLE
Is homing supported in "direct" mode?

### ISSUE THREAD

**Issue by djvine** [epics-motor/motorAcsTech80#2]
I have an air bearing rotary stage from PI that uses an SPii controller.

I'm using the "direct" command mode and it looks like some features such as homing are only supported by the "buffer" command mode:

```
switch (command)
            {
        	case MOVE_ABS:
        	  if (cntrl-&gt;cmndMode == BUFFER)
        	    sprintf(buff, "Done(%d)=0;target_pos(%d)=%d;opReq(%d)=%d;", axis, axis, intval, axis, OP_ABS_MOVE);
          	  else
           	    sprintf(buff, "ptp (%d), %d;", axis, intval);
        	  break;

               case MOVE_REL:
          	  if (cntrl-&gt;cmndMode == BUFFER)
             	    sprintf(buff, "Done(%d)=0;target_pos(%d)=%d;opReq(%d)=%d;", axis, axis, intval, axis, OP_REL_MOVE);
             	  else
          	    sprintf(buff, "ptp/r (%d), %d;", axis, intval);
            	 break;

        	case HOME_FOR:
            	  if (cntrl-&gt;cmndMode == BUFFER)
         	    sprintf(buff, "Done(%d)=0;opReq(%d)=%d;", axis, axis, OP_HOME_F);
         	  break;

        	case HOME_REV:
          	  if (cntrl-&gt;cmndMode == BUFFER)
             	    sprintf(buff, "Done(%d)=0;opReq(%d)=%d;", axis, axis, OP_HOME_R);
```

Do I have that right?

**Comment by kmpeters** [comment]
I believe you have that right.  Some features are only supported in "buffer" mode.

Is the controller fairly new?  The [motorAcsMotion](https://github.com/epics-motor/motorAcsMotion) module should work with most new ACS Motion controllers and doesn't require any programs to be installed on the controller.  I recommend using the master branch; there should be a new release soon(ish).

**Comment by djvine** [comment]
Ah ok, I didn't know that module was also Spii.

I'll use that.

**Comment by kmpeters** [comment]
Newer ACS controllers have a number of homing options, but homing to a dedicated home switch isn't included.  I haven't written a custom routine for that yet.  The support does allow EPICS to start/stop programs running on the controller.
